### ISSUE TITLE
"RegionHoles" property missing in AnnulusMesh generated meshes

### ISSUE THREAD

**Issue by ruebenko** [c3m-labs/MeshTools#7]
When AnnulusMesh creates it's mesh it should also set the `RegionHoles` property. See
[this](https://mathematica.stackexchange.com/a/210699/18437) for more details.

**Comment by PintarM** [comment]
Thank you for notification, I will fix this in `AnnulusMesh` and other functions that may have the same problem.

**Comment by ruebenko** [comment]
One thing to think about is to set the region holes back to None once an extrusion happens, I think.

**Comment by PintarM** [comment]
Good catch, thank you!

**Comment by PintarM** [comment]
Fixed in 242bb955cf468889bb3b712641046938eaf196fc
